export const level1 = {
  name: "Level 1",
  spawnPoint: { x: 500, z: 320, y: 0, rotation: 0 },
  textures: [
    { type: "wall", name: "north", path: "WALL01.png" },
    { type: "wall", name: "south", path: "WALL01.png" },
    { type: "wall", name: "east", path: "WALL02.png" },
    { type: "wall", name: "west", path: "WALL02.png" },
    { type: "floor", name: "floor", path: "FLOOR.png" },
  ],
  rooms: [
    {
      walls: [
        {
          x: 400,
          y: 0,
          z: 340,
          width: 160,
          height: 5,
          rotation: 1.5707963267948966,
          texture: "west",
          depth: 0,
          normal: { x: 1, y: 0, z: 0 },
        },
        {
          x: 500,
          y: 0,
          z: 420,
          width: 200,
          height: 5,
          rotation: 0,
          texture: "north",
          depth: 0,
          normal: { x: 0, y: 0, z: 1 },
        },
        {
          x: 600,
          y: 0,
          z: 340,
          width: -160,
          height: 5,
          rotation: 1.5707963267948966,
          texture: "west",
          depth: 0,
          normal: { x: 1, y: 0, z: 0 },
        },
        {
          x: 500,
          y: 0,
          z: 260,
          width: -200,
          height: 5,
          rotation: 0,
          texture: "north",
          depth: 0,
          normal: { x: 0, y: 0, z: 1 },
        },
      ],
      floors: [
        {
          x: 500,
          y: -1,
          z: 340,
          width: 200,
          length: 160,
          texture: "floor",
          rotation: -1.5707963267948966,
        },
      ],
    },
  ],
  entities: [
    {
      type: "player",
      position: { x: 2, y: 0, z: 2 },
      properties: { speed: 5, health: 100 },
    },
    {
      type: "enemy",
      position: { x: 8, y: 0, z: 8 },
      properties: { ai: "patrol", damage: 10 },
    },
  ],
};
